### PR TITLE
fix: prevent new workers from writing to closed pool

### LINKED ISSUE #94: ERR_IPC_CHANNEL_CLOSED: Channel closed
Error below comes up quite often on Vitest's codebase. Tests themselves are passing fine, but this error is visible on test logs. My initial guess is that Tinypool is shutting down before workers have finished loading user's entrypoint. These workers are likely the idle workers that are kept ready for next pool runs.

These errors should only come up when multiple pools are nested, e.g. running Tinypool in Tinypool. 

```
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at target.send (node:internal/child_process:754:16)
    at file:///<root>/vitest/node_modules/.pnpm/tinypool@0.9.0/node_modules/tinypool/dist/entry/process.js:29:7
Emitted 'error' event on process instance at:
    at node:internal/child_process:758:35
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

As fix we could try adding a no-op callback here just to ignore these errors:

https://github.com/tinylibs/tinypool/blob/ea05a00c86d10465674b6747538c7b18902bd5ae/src/entry/process.ts#L42-L46

https://nodejs.org/api/process.html#processsendmessage-sendhandle-options-callback

### PR DESCRIPTION
**Pull request by AriPerkkio**
- Fixes #94

### CODE REVIEW

File: src/entry/process.ts [hunk 1]
```diff
@@ -39,11 +39,16 @@ process.on('message', (message: IncomingMessage) => {
...
+      send!(
+        <OutgoingMessage>{
+          ready: true,
+          source: 'pool',
+          __tinypool_worker_message__: true,
+        },
+        () => {
+          // Ignore errors coming from closed channel
+        }
+      )
```
Comment (AriPerkkio) [inline src/entry/process.ts:51]: Another approach is to check `process.channel` here. Though now new `Error: write EPIPE` errors come up randomly when pool is closing. 🤔
